name: Deploy docs
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-deploy:
        permissions:
            contents: write
            pages: write
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
                with:
                    node-version: 20

            - run: npm ci
            - run: npm run build

            - name: Add CNAME
                run: echo "larajax.org" > .vitepress/dist/CNAME

            - name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: .vitepress/dist
                    force_orphan: true
